version: '3.7'

services:
  dev:
    container_name: next_dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - '.:/app'
      - '/app/node_modules'
